### PR TITLE
Added a license file using the BSD-3-Clause (new) license template

### PR DESCRIPTION
**Pull request by stackh34p**
Hello Atif 

First, thank you for creating this useful library and choosing an open-source license for it. 

I am very strict when it comes to project licenses and this is usually the first thing I check before adopting an open-source library or component in my own work. I am using this particular library for quite some time and I am familiar with its license terms, but I've had bad luck locating its source-code repository for quite some time, until today (😊 ). 

Currently, the project's license terms are available in the [COPYING.txt](https://github.com/atifaziz/LINQBridge/blob/master/COPYING.txt) file, which is not automatically recognized by GitHub as the BSD-3-Clause license (I believe this is the right license this project is released under). The purpose of this commit is to make it more obvious for developers, who browse the repository, to identify the license -- its name should now appear on the right pane in the repository page and will link to the BSD-3-Clause license text. I achieved this using the BSD-3-Clause (new) license template form that is provided by GitHub, and changed copyright date to 2007-2020 (I was asked in the license template form and assumed the project is still active so the end-date should be 2020).

I'm hoping my cosmetic contribution is all fine with you.

### CODE REVIEW

**Review by atifaziz — CHANGES_REQUESTED** [review]
> I am very strict when it comes to project licenses and this is usually the first thing I check before adopting an open-source library or component in my own work.

I commend your due diligence.

GitHub uses [Licensee](https://github.com/licensee/licensee) to detect the license of a project. I don't think the file name is the issue here as it [accepts a license in a file named `COPYING.txt` (in addition to other variants)](https://github.com/licensee/licensee/blob/1c5595ad09b9178fbb1dc1e3f941d1403dbf8f60/lib/licensee/project_files/license_file.rb#L27-L45). With this PR, it would be confusing (for those not relying on GitHub) to have two files (`LICENSE` and `COPYING.txt`) with similar license terms.

I tried to understand what may be throwing `licensee` off and here's what I found from running it against the project. I did this in a Docker container so you can follow the steps.

I started by running an interactive shell session using the Debian (Stretch) image:

    docker run --rm -it debian:stretch

The remaining commands were all run in the shell of the image.

I installed the [dependencies needed for `licensee`](https://github.com/licensee/licensee/tree/3a028b6cb9c2c5d8cd1905faed735fdc23bc133e#installation) (I also added cURL so we can download `COPYING.txt` in a later step):

    apt-get update \
    && apt-get install -y curl zlib1g-dev git ruby bundler cmake pkg-config libssl-dev

Next, I installed `licensee`:

    gem install licensee

I create a directory for the project and switched to it:

    mkdir LINQBridge && cd LINQBridge

I downloaded a copy of just the license (no need for an entire clone) into that directory:

     curl -OsSL https://raw.githubusercontent.com/atifaziz/LINQBridge/b5828699529e99d442289cb27c723dc4a7e46ef9/COPYING.txt

Finally, I ran `licensee` and got this output:

    License:        NOASSERTION
    Matched files:  COPYING.txt
    COPYING.txt:
      Content hash:  1d4a8d33c74979252df372edc444143dc229f140
      License:       NOASSERTION
      Closest non-matching licenses:
        BSD-3-Clause similarity:        91.76%
        BSD-4-Clause similarity:        90.70%
        BSD-3-Clause-Clear similarity:  90.42%

You can see here clearly that `COPYING.txt` was used for detecting the license and it seems to find a 91+% match BSD-3-Clause license terms. I am guessing that's not good enough ([threshold seems to be 98%](https://github.com/licensee/licensee/blob/cf4bbf38ff1336ae9f53c1278897a6ef94bbc413/lib/licensee.rb#L20-L21)), which is why the “License” field reads `NOASSERTION`.

`licensee` has a nice feature where you can ask for a diff from the expected license, so I did that next:

    licensee diff --license bsd-3-clause 2>/dev/null

However, this produced an error. It looks like there's a UTF-8 BOM in `COPYING.txt` that throws `licensee diff` off so I removed that (by skipping first 3 characters with `tail`) next with:

    (rm COPYING.txt; tail -c +4 > COPYING.txt) < COPYING.txt

The I ran `licensee diff` again:

    licensee diff --license bsd-3-clause 2>/dev/null

and got the following output:

    Comparing to BSD 3-Clause "New" or "Revised" License:
    Input Length:      1504
    License length:    1420
    Similarity:      91.76%
    diff --git a/LICENSE b/LICENSE
    index e57f70e..f468c51 100644
    --- a/LICENSE
    +++ b/LICENSE
    @@ -1,19 +1,20 @@
    {+linqbridge copyright (c) 2007-2009, atif aziz, joseph albahari all rights+}
    {+reserved.+} redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met: [---]{+*+}
    redistributions of source code must retain the above copyright notice, this list
    of conditions and the following disclaimer. [---]{+*+} redistributions in binary form
    must reproduce the above copyright notice, this list of conditions and the
    following disclaimer in the documentation and/or other materials provided with
    the distribution. [---]{+*+} neither the name of the [-copyright holder-]{+original authors+} nor the names of
    its contributors may be used to endorse or promote products derived from this
    software without specific prior written permission. this software is provided by
    the copyright holders and contributors "as is" and any express or implied
    warranties, including, but not limited to, the implied warranties of
    merchantability and fitness for a particular purpose are disclaimed. in no event
    shall the copyright holder or contributors be liable for any direct, indirect,
    incidental, special, exemplary, or consequential damages (including, but not
    limited to, procurement of substitute goods or services; loss of use, data, or
    profits; or business interruption) however caused and on any theory of
    liability, whether in contract, strict liability, or tort (including negligence
    or otherwise) arising in any way out of the use of this software, even if
    advised of the possibility of such damage.

Summary of changes are:

1. Leading copyright notice
2. “original authors” instead of “copyright holder”
3. Bullets using asterisk (`*`) as opposed to hyphen (`-`)

I was surprised by 1, since [`licensee` is designed to strip such leading notices](
https://github.com/licensee/licensee/blob/3a028b6cb9c2c5d8cd1905faed735fdc23bc133e/lib/licensee/content_helper.rb). I noticed the project name coming before “Copyright” so I stripped that next:

    (rm COPYING.txt; tail -c +12 > COPYING.txt) < COPYING.txt

and tried again:

    licensee diff --license bsd-3-clause 2>/dev/null

This time, the match was 99+%:

    Comparing to BSD 3-Clause "New" or "Revised" License:
    Input Length:      1420
    License length:    1420
    Similarity:      99.15%
    diff --git a/LICENSE b/LICENSE
    index e57f70e..3aa7dd8 100644
    --- a/LICENSE
    +++ b/LICENSE
    @@ -1,10 +1,10 @@
    redistribution and use in source and binary forms, with or without modification,
    are permitted provided that the following conditions are met: [---]{+*+} redistributions
    of source code must retain the above copyright notice, this list of conditions
    and the following disclaimer. [---]{+*+} redistributions in binary form must reproduce
    the above copyright notice, this list of conditions and the following disclaimer
    in the documentation and/or other materials provided with the distribution. [---]{+*+}
    neither the name of the [-copyright holder-]{+original authors+} nor the names of its contributors may
    be used to endorse or promote products derived from this software without
    specific prior written permission. this software is provided by the copyright
    holders and contributors "as is" and any express or implied warranties,

So now just running `licensee` alone (which is same as `licensee detect`) printed:

    License:        BSD-3-Clause
    Matched files:  COPYING.txt
    COPYING.txt:
    Content hash:  3e03b4d347a6b2451949f875c4af339c4df3294b
    Attribution:   Copyright (c) 2007-2009, Atif Aziz, Joseph Albahari
    Confidence:    99.15%
    Matcher:       Licensee::Matchers::Dice
    License:       BSD-3-Clause
    Closest non-matching licenses:
        BSD-3-Clause similarity:        99.15%
        BSD-4-Clause similarity:        90.98%
        BSD-3-Clause-Clear similarity:  90.35%

And now we have a match for BSD-3-Clause with 99% confidence! Even the “Attribution” field is picking up the copyright notice nicely.

I am quite certain that if you make the minimal changes of:

- removing the UTF-8
- removing the project name before the copyright notice

then GitHub will happily display the detected license.

Could I ask you to make just those minimal changes to `COPYRIGHT.txt`? I'd be happy to merge soon after. Thanks!

**Comment by stackh34p** [comment]
Yep, all this sounds very reasonable. I will try to accomplish this later today :) .  I agree that two license files would be confusing indeed.

**Comment by stackh34p** [comment]
And done :) Your knowledge of GitHub using Licensee really made this a baby's game

**Review by atifaziz — APPROVED** [review]
Thank you very much for this PR and your [prompt follow-up](https://github.com/atifaziz/LINQBridge/pull/29/commits/e4d865444a940de0452bfe887b88b8e032bab90b).

**Pull request merged**
